version: "2"
services:
 mongo:
  image: mongo
  ports:
   - "27017:27017"
 web:
  build: .
  volumes:
   - ./app:/app
   - /app/node_modules
  ports:
   - "3000:3000"
   - "3001:3001"
   - "9000:9000"
  depends_on:
   - mongo
  links:
   - mongo
